In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import joblib

dataset=pd.read_csv(r'C:\Users\UDITHA PC\Desktop\CM\Heart Risk Prediction\cardio_dataset.csv').values

data=dataset[:,0:7]
target=dataset[:,7]

print(data[:5])
print(target.shape)

target=np.reshape(target,(-1,1))
print(target)

train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.2)
model=LinearRegression()
model.fit(train_data,train_target)

predicted_target=model.predict(test_data)
print(predicted_target)
print(test_target)

r2=r2_score(test_target,predicted_target)
print(r2)

joblib.dump(model,'heart_risk_prediction_regression_model.sav')

[[  2.  48. 236.  66.   0.   2.   0.]
 [  1.  48. 260.  51.   0.   2.   1.]
 [  1.  44. 187.  49.   1.   2.   0.]
 [  2.  42. 216.  57.   1.   2.   0.]
 [  2.  56. 156.  42.   0.   2.   0.]]
(6644,)
[[ 1.1]
 [ 7. ]
 [ 7. ]
 ...
 [30.6]
 [23.8]
 [ 1. ]]
[[24.48208534]
 [-7.19677906]
 [ 6.80824746]
 ...
 [ 1.86581858]
 [23.7408024 ]
 [15.45140522]]
[[19.9]
 [ 1. ]
 [ 5.4]
 ...
 [ 2.2]
 [44.2]
 [11.6]]
0.7551098220771375


['heart_risk_prediction_regression_model.sav']